### ISSUE TITLE
support system wide installation

### ISSUE THREAD

**Issue by blshkv** [ShielderSec/webtech#15]
I'm thinking to push your software (thanks for hard work!) to Pentoo Linux.
We install all files into system location so that a regular user would run it later.

I noticed that webtech has an update feature which will try to modify certain files.
That basically will fail because a regular user does not have a write access.
```
DATABASE_FILE = os.path.join(INSTALLATION_DIR, "webtech.json")
WAPPALYZER_DATABASE_FILE = os.path.join(INSTALLATION_DIR, "apps.json")
```

What you should do instead, is to create a local ~./webtech folder use it for any custom config files and updates.

Please consider.

**Comment by blshkv** [comment]
For more details, see the following https://github.com/pentoo/pentoo-overlay/issues/596

**Comment by TheZ3ro** [comment]
this seems a good idea, we will work on it! Thanks
