### ISSUE TITLE
join forces with wappalyzer

### ISSUE THREAD

**Issue by blshkv** [ShielderSec/webtech#16]
wappalyzer been around for much longer, so I suspect that they have a bigger database.

Apparently, both databases in JSON format and it may be make some sense to join forces and use one database?
https://github.com/AliasIO/wappalyzer/blob/master/src/apps.json

For your consideration please

**Comment by blshkv** [comment]
ok, I found your blogpost:
https://www.shielder.it/blog/webtech-identify-technologies-used-on-websites/
"we wanted a modular tool capable of reading Wappalyzer database".

so it's almost identical. However, you have to sync the databases periodically. Looks like an unnecessary step if you do it manually.

Is any better way?

**Comment by TheZ3ro** [comment]
Hi!

We support and use Wappalyzer's database but we are not 100% compatible, also some regex inside the DB are broken for us so we need to fix them in our own db.
Also note that our use case is different from Wappalyzer's.

So I don't undertstand how should we join forces with Wappalyzer? Thanks.

**Comment by blshkv** [comment]
Yeah, I was thinking... Would it be possible to make it 100% compatible and pull app.json from their repository directly?

**Comment by TheZ3ro** [comment]
It's not really easy and not in our plan at the moment. 😃

**Comment by blshkv** [comment]
Ok, I tried at least ;)
