### ISSUE TITLE
Database can not be updated because apps.json no longer exists.

### ISSUE THREAD

**Issue by darkshram** [ShielderSec/webtech#22]
The following URL, defined in database.py, does not exist anymore:

https://raw.githubusercontent.com/AliasIO/Wappalyzer/master/src/apps.json

Therefore database can not be updated

Fedora recently added webtech to their repositories, but webtech can not used because the included database is older than 30 days and program tries and fails to update database before doing anything.

Replacing https://raw.githubusercontent.com/AliasIO/Wappalyzer/master/src/apps.json with https://raw.githubusercontent.com/ShielderSec/webtech/master/webtech/apps.json in webtech/database.py helps solve the issue.

**Comment by TheZ3ro** [comment]
Thanks for the report. I will look into and deploy the fix asap
