### ISSUE TITLE
The Wappalyzer database seems offline.

### ISSUE THREAD

**Issue by pokrakos** [ShielderSec/webtech#35]
The Wappalyzer database seems offline.

**Comment by TheZ3ro** [comment]
Apparently the Wappalyzer repository got pulled off Github and become closed source.
We are looking for an alternative. In the meantime, webtech should work anyway with the local database (lastest version downloaded from Wappalyzer)

**Comment by TheZ3ro** [comment]
This got fixed in https://github.com/ShielderSec/webtech/commit/9a020aa91ba4faed4bcdf1cb081f6dd5ac6edf00
webtech now download its database file from https://github.com/enthec/webappanalyzer/

We will soon draft a new release `1.3.4` on PyPI that can be installed with
`pip3 install -U webtech`
