### ISSUE TITLE
Library Usage [Question]

### ISSUE THREAD

**Issue by arbazkiraak** [ShielderSec/webtech#4]
Hi,

> What is the correct way to use the library in Python right away?

```
wt = webtech.WebTech()
wt.output_format = webtech.utils.Format['json']
wt.start_from_url('https://facebook.com')
```

```
AttributeError: 'WebTech' object has no attribute 'USER_AGENT'
```

Thanks!

**Comment by TheZ3ro** [comment]
It seems that with the 1.2.4 update I've broken some things. Sorry about that.

I've pushed a fix in the `dev` branch. (https://github.com/ShielderSec/webtech/commit/d4345f1f9a578e76bc4ebc6d029c13b806f818d7#diff-8cc8913f1292c593f09fecc4ddaefe4fR82)
You can clone the repository, `git checkout dev; git pull`, and install it with `python3 ./setup.py install --user`

I've also added a simple example:
https://github.com/ShielderSec/webtech/blob/dev/webtech_example.py

I will test this new fix and release a new version ASAP, let me know if it works!
Also, for the new version I will write a small paragraph in the readme about using it as a library.

Thanks for the feedback. :100:

**Comment by arbazkiraak** [comment]
That's great, Thanks Mate 

One more suggestion would add an exception handling rule while making requests to prevent `ConnectionError` so that our script will continue scanning next domains from list and add the timeout function.

```
try:
     response = get(url, headers=headers, cookies=cookies, verify=False, allow_redirects=True)
except requests.exceptions.RequestException as e:
    print('There was an error while making request:',str(e))
```

**Comment by TheZ3ro** [comment]
I've update the dev branch, now a library can specify the desired timeout and catch connection errors (the library only triggers the exception, it's a script duty to deal with it)

I've updated the example to reflect this changes
https://github.com/ShielderSec/webtech/blob/1dfd2ec2cf55146f6706a95c3aa494e53a9537fb/webtech_example.py

**Comment by TheZ3ro** [comment]
Merged into master, closing this issue 😄 🎉
